[tool.black]
line-length = 120
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
line_length = 120
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = true

[tool.pytest.ini_options]
minversion = "7.0"
python_files = "*.py"
testpaths = [
    "tests"
]
pythonpath = [
    "."
]
log_cli=true
log_level=0
